name: CircleFFA
version: '${project.version}'
main: me.itsglobally.circleffa.CircleFFA
load: STARTUP
commands:
  setLayout:
    description: "gay"
  toggleBm:
    permission: circleffa.togglebm
    aliases:
      - tbm
  kms:
    description: "gay"
  changeMap:
    description: "gay"
  statsreset:
    permission: circleffa.statsreset
permissions:
  circleffa.togglebm:
    default: op
  circleffa.statsreset:
    default: op