name: CircleFFA
version: '${project.version}'
main: me.itsglobally.circleffa.CircleFFA
load: STARTUP
depend:
  - DiscordSRV
commands:
  setLayout:
    description: "gay"
  toggleBm:
    permission: circleffa.togglebm
    aliases:
      - tbm
  kms:
    description: "gay"
  changeMap:
    description: "gay"
  statsreset:
    permission: circleffa.statsreset
  setstar:
    permission: circleffa.setstar
  setxp:
    permission: circleffa.setxp
  ffa:
    description: "ga"
permissions:
  circleffa.togglebm:
    default: op
  circleffa.statsreset:
    default: op
  circleffa.setstar:
    default: op
  circleffa.setxp:
    default: op