name: CircleFFA
version: '${project.version}'
main: me.itsglobally.circleffa.CircleFFA
load: STARTUP
depend:
  - DiscordSRV
softdepend:
  - "PlaceholderAPI"
commands:
  setLayout:
    description: "gay"
  ffa:
    description: "gay"
    aliases:
      - kms
permissions:
  circleffa.togglebm:
    default: op
  circleffa.statsreset:
    default: op
  circleffa.setstar:
    default: op
  circleffa.setxp:
    default: op
  circleffa.admin:
    default: op
  circleffa.changemap:
    default: op