name: CircleFFA
version: '${project.version}'
main: me.itsglobally.circleffa.CircleFFA
load: STARTUP
commands:
  setLayout:
    permission: circleffa.setlayout
  toggleBm:
    permission: circleffa.togglebm
    default: op
  kms:
    permission: circleffa.kms