name: CircleFFA
version: '${project.version}'
main: me.itsglobally.circleffa.CircleFFA
load: STARTUP
commands:
  setLayout:
    description: "gay"
  toggleBm:
    permission: circleffa.togglebm
    aliases:
      - tbm
    default: op
  kms:
    description: "gay"
  changeMap:
    description: "gay"